### ISSUE TITLE
Python scripting support for GDB

### ISSUE THREAD

**Issue by cristianadam** [StephanTLavavej/mingw-distro#73] opened 2019-11-28 16:16 UTC
I tried using the provided GDB with Qt Creator, and Qt Creator complained with:

```
>&"python sys.path.insert(1, 'C:/Qt/qtcreator-4.11.0-rc1/share/qtcreator/debugger/')\n"
>&"Python scripting is not supported in this copy of GDB.\n"
>9^error,msg="Python scripting is not supported in this copy of GDB."

>&"python sys.path.append('C:/MinGW/bin/data-directory/python')\n"
>&"Python scripting is not supported in this copy of GDB.\n"
>10^error,msg="Python scripting is not supported in this copy of GDB."

>&"python from gdbbridge import *\n"
>&"Python scripting is not supported in this copy of GDB.\n"
>11^error,msg="Python scripting is not supported in this copy of GDB."

>&"python theDumper.loadDumpers({\"token\":12})\n"
>&"Python scripting is not supported in this copy of GDB.\n"
>12^error,msg="Python scripting is not supported in this copy of GDB."
 The selected build of GDB does not support Python scripting. It cannot be used in Qt Creator.
dNOTE: ENGINE SETUP FAILED
dState changed from EngineSetupRequested(1) to EngineSetupFailed(2)
<Debugging has failed.
dState changed from EngineSetupFailed(2) to DebuggerFinished(17)
```

It would be great if Qt Creator would be able to use this toolchain. 

I don't know if Visual Studio Code uses the same Python API to talk to GDB.

**Comment by StephanTLavavej** [comment] 2019-11-28 19:32
Duplicate of #1. I'm told that Python's support for MinGW is deficient, I don't know how to build this without an installer, and (most importantly) I don't have enough free time to maintain large things that I don't use.

**Closed by StephanTLavavej** 2019-11-28 19:32 UTC
