### ISSUE TITLE
OpenMP Support

### ISSUE THREAD

**Issue by RoyiAvital** [StephanTLavavej/mingw-distro#40] opened 2017-07-04 21:06 UTC
Hello,

I tried compiling a file using `gcc` and I got the following error:

> fatal error: omp.h: No such file or directory

I looked for omp.h in all the files extracted from your installer and I couldn't find it.
Could it be that OpenMP Support is missing from your distribution?

Thank You.

**Comment by StephanTLavavej** [comment] 2017-07-04 21:19
Duplicate of #32. Related to #26. I can't enable OpenMP as long as it requires pthreads, which I don't build.

**Comment by RoyiAvital** [comment] 2017-07-04 21:42
I see...

I thought I had the holy land :-).

Is there distribution like yours (Portable with bat file to create properly configured environment) with OpenMP support?

What you created is the perfect experience, but I really need OpenMP.

Thank You.

**Comment by dokipen3d** [comment] 2017-09-03 00:46
After seeing the last comment on [#26](https://github.com/StephanTLavavej/mingw-distro/issues/26 ) could this maybe pretty please be reconsidered? :)

**Comment by StephanTLavavej** [comment] 2017-09-03 05:21
Maybe, but I'll need either lots of free time, or someone telling me exactly how to alter my build scripts.

**Comment by dokipen3d** [comment] 2017-09-03 07:28
ok thanks, I'm going to have a go at running the scripts now and see how it goes :)

**Comment by dokipen3d** [comment] 2017-09-03 21:07
I was able to make a small modification to the build script and now I have pthreads in gcc to enable openmp! I'll make a pull request later today so we can test it and see if there are any issues.


<img width="411" alt="screen shot 2017-09-04 at 9 04 45 am" src="https://user-images.githubusercontent.com/7567809/30006615-469e5212-9150-11e7-8b9f-8d1511fc57f5.png">

**Comment by RoyiAvital** [comment] 2017-09-03 21:13
This is lovely.

@dokipen3d , Thank You!

**Comment by dokipen3d** [comment] 2017-09-03 21:33
done [https://github.com/StephanTLavavej/mingw-distro/pull/46](https://github.com/StephanTLavavej/mingw-distro/pull/46)

Now lets find if there is anything wrong with it. If anyone wants to send me some things to compile and run, I can give it a go.

**Comment by RoyiAvital** [comment] 2017-09-03 21:40
@dokipen3d ,
This is great news.

You can try this:
https://github.com/RoyiAvital/Projects/tree/master/ImageToColumns

Thank You.

**Comment by dokipen3d** [comment] 2017-09-03 23:13
Well it compiles fine. Not sure if it runs though! I've tried a few openmp helloworlds just printing info about the threads and it all seems fine. I've got my own project I'll try next which uses it a lot.

<img width="400" alt="screen shot 2017-09-04 at 11 12 05 am" src="https://user-images.githubusercontent.com/7567809/30007420-f1c379fe-9161-11e7-8bb5-a2a7424164f3.png">

**Comment by StephanTLavavej** [comment] 2017-10-02 06:57
I believe I can enable winpthreads and OpenMP in distro 15.2, thanks to your pull request.

**Comment by dokipen3d** [comment] 2017-10-02 07:56
Excellent thanks so much STL!

**Closed** 2017-10-03 23:11 UTC
Labels: fixed

**Comment by RoyiAvital** [comment] 2018-04-08 12:52
Guys,

Is the issue of MinGW64 with AVX code on Windows 64 relevant to this distribution as well?
I encountered this lately and I can't get a good picture what's going on.

Please see my post here - https://github.com/Alexpux/MSYS2-packages/issues/1209#issuecomment-379547589.

**Comment by StephanTLavavej** [comment] 2018-04-08 20:14
Please don’t hijack issues (even ones you’ve opened) for unrelated issues. In this case, I agree with the MSYS2 maintainers - this is an upstream GCC issue and should be reported to upstream GCC maintainers with a proper self-contained test case.

**Comment by RoyiAvital** [comment] 2018-04-08 20:43
I'm sorry.
Just wanted to know if you're aware of this or maybe you have solved it in your customized distribution.

I really hope someone will solve this.

**Comment by StephanTLavavej** [comment] 2018-04-08 20:53
I don't know anything about this and can't fix it. Don't hope - instead, report the bug properly.
