### ISSUE TITLE
GCC 11 support

### ISSUE THREAD

**Issue by wjx0912** [StephanTLavavej/mingw-distro#85] opened 2021-04-01 02:00 UTC
https://linuxreviews.org/GCC_11_Will_Be_Set_In_Stone_On_November_15th

the gcc11 will release immediately, wish your great job, thanks

**Comment by wjx0912** [comment] 2021-04-21 00:47
https://gcc.gnu.org/

gcc 11.1 release

**Comment by StephanTLavavej** [comment] 2021-09-13 07:36
Duplicate of #83, see my update there: https://github.com/StephanTLavavej/mingw-distro/issues/83#issuecomment-917921046 .

**Closed by StephanTLavavej** 2021-09-13 07:36 UTC
Labels: duplicate
